name: flutter_unit
description: A new Flutter application.
publish_to: none
version: 2.9.3+1
author: 张风捷特烈 <1981462002@qq.com>
homepage: https://juejin.cn/user/149189281194766/posts


environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4
  flutter_bloc: ^8.1.3 # 状态管理
  equatable: ^2.0.5 # 相等辅助
  stream_transform: ^2.1.0
  archive: ^3.3.9 # 解压
  package_info_plus: ^4.1.0 # 应用包信息
  r_upgrade: ^0.3.8 # 应用升级
  webview_flutter: ^4.2.4
  sqflite: ^2.3.0 # 数据库
  sqflite_common_ffi: ^2.3.0+2 # 数据库
  shared_preferences: ^2.2.1 # xml 固化
  path_provider: ^2.1.1  # 路径
  dio: ^5.3.2 # 网络请求
  jwt_decoder: ^2.0.1 # jwt 解析
  connectivity_plus: ^4.0.2
  refresh: ^1.0.1
  toggle_rotate: ^1.0.1
  flutter_star: ^1.0.2 # 星星组件
  dash_painter: ^1.0.2
  wrapper: ^1.0.2
  yaml_modify: ^1.0.1
  url_launcher: ^6.1.14 # url
  share_plus: ^7.1.0 # 文字分享

  flutter_svg: ^2.0.7
  intl: ^0.18.0
  platform: ^3.1.0
  image: ^4.0.17
  flutter_spinkit: ^5.2.0 # loading
  flutter_markdown: ^0.6.4 # markdown
#  file_selector: ^0.9.2+2
  file_picker: ^5.5.0
  widget_repository:
    path: packages/widget_repository
  utils:
    path: packages/utils
  storage:
    path: packages/storage
  widgets:
    path: packages/widgets
  artifact:
    path: packages/artifact
  algorithm:
    path: packages/algorithm
  authentication:
    path: packages/authentication
  app:
    path: packages/app
  app_update:
    path: packages/app_update
  components:
    path: packages/components
  widget_module:
    path: packages/widget_module
#  old_fancy_mobile_ui:
#    path: packages/old_fancy_mobile_ui

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4



dependency_overrides:
  intl: ^0.19.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
    - assets/images/head_icon/
    - assets/images/widgets/
    - assets/flutter.db
    - assets/version.json

  fonts: # 配置字体，可配置多个，支持ttf和otf,ttc等字体资源
    - family: TolyIcon
      fonts:
        - asset: assets/iconfont/toly_icon.ttf
    - family: IndieFlower #字体名
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: BalooBhai2 #字体名
      fonts:
        - asset: assets/fonts/BalooBhai2-Regular.ttf
    - family: Inconsolata #字体名
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
    - family: Neucha #字体名
      fonts:
        - asset: assets/fonts/Neucha-Regular.ttf
    - family: ComicNeue #字体名
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf
    - family: CHOPS
      fonts:
        - asset: assets/fonts/CHOPS.TTF













